version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004
configuration: Release
platform: x64
before_build:
- ps: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
- ps: nuget restore PasswordChanger1C.sln
build:
  verbosity: normal